### ISSUE TITLE
「スケジュールタス」タイポ

### ISSUE THREAD

**Issue by junichimura** [laravel-ja/ja-docs-5.8#1]
小さなタイポ箇所を見つけました。

▼問題の箇所
URL: https://readouble.com/laravel/5.8/ja/releases.html#laravel-5.8
「スケジューラのデフォルトタイムゾーン」の項目
「しかしながら、スケジュール済みの全タスクに対して、同じタイムゾ…このメソッドは、スケジュールタスに対し指定…」の後半部分が「スケジュールタス」という表記になっている。

▼望ましい修正方法
「スケジュールタス」の表記を「スケジュールタスク」へ修正する。

以上、ご確認ください。

**Comment by HiroKws** [comment]
ありがとうございます。修正しました。
