### ISSUE TITLE
validation.php言語ファイルーafter_or_equal

### ISSUE THREAD

**Issue by ecormaksin** [laravel-ja/ja-docs-5.8#2]
https://readouble.com/laravel/5.8/ja/validation-php.html

`'after_or_equal'       => ':attributeには、:date以前の日付を指定してください。',`

以下ではないでしょうか。

`'after_or_equal'       => ':attributeには、:date以降の日付を指定してください。',`

**Comment by HiroKws** [comment]
ありがとうございます。修正しました。
なお、言語ファイルの翻訳ページは、ドキュメントではなくreadouble.comのオリジナルページであるため、このリポジトリの内容には反映されません。

**Comment by ecormaksin** [comment]
ご対応くださり、ありがとうございます。
