### ISSUE TITLE
readouble.com フッタでの名前タイポ

### ISSUE THREAD

**Issue by paichi81** [laravel-ja/ja-docs-5.8#3]
readouble.com/laravel の日本語訳各ページ下部がすべて

> Licensed by MIT License. Copyright at Tayllor Otwell(Original) and Hirohisa kawase(Translation), 2018.

となっています。
**Taylor**が正しいスペルではないでしょうか。

**Comment by HiroKws** [comment]
ありがとうございます。修正しました。
