### ISSUE TITLE
TYPO報告

### ISSUE THREAD

**Issue by dyoshikawa** [laravel-ja/ja-docs-5.8#4]
いつもありがとうございます。

https://readouble.com/laravel/5.8/ja/scout.html

こちらの `カスタムエンジン` の項目で、

> カスタムエンジンが実装する必要のある、７つのメソッドを持っています

こちら `7つ` ではなく `8つ` ではないでしょうか。

**Comment by HiroKws** [comment]
ご指摘ありがとうございます。実は、原文が７のままですので、そのとおりに訳してあります。原文が修正された時点で、変更いたします。

翻訳は基本的に原文に合わせる方針を取っています。日本語版で原文の間違いを吸収してしまうと、その管理で手間がかかるためです。原文修正まで、しばらくお待ちください。

2019年5月7日(火) 14:45 dyoshikawa <notifications@github.com>:

**Comment by dyoshikawa** [comment]
ご返信ありがとうございます。
原文も7だったのですね。承知しました。

**Comment by HiroKws** [comment]
なかなか原文が修正されないため、原文リポに対し修正のプルリクを送り、受領されました。その反映を受け８へ変更しました。
