### ISSUE TITLE
Laravelインストーラの「ディレクト」

### ISSUE THREAD

**Issue by junichimura** [laravel-ja/ja-docs-5.8#5]
小さなタイポ箇所を見つけました。

▼問題の箇所
URL: https://readouble.com/laravel/5.8/ja/installation.html?fbclid=IwAR3tKRYzXMMowb87G3011HsrPng60yZBcn8MqBdXqFF6hYr9qdxSdxOZREg#installing-laravel
「Laravelインストーラ」の項目
※問題個所を太字で表記します。
「インストールし終えたら、laravel newコマンドにより、指定したディレクトリに真新しいLaravelプロジェクトを作成できます。例えば、laravel new blogを実行すると、blogという名前の **ディレクト** へ、必要とするパッケージが全部揃った、真新しいLaravelがインストールされます。」

▼望ましい修正方法
「ディレクト」の表記を、原文に合わせ「ディレクトリ」へ修正する。

以上、ご確認ください。

**Comment by HiroKws** [comment]
ありがとうございます。修正します。
