### ISSUE TITLE
Laravel Horizonのページに1個所リンク切れがある

### ISSUE THREAD

**Issue by magai** [laravel-ja/ja-docs-5.8#6]
> Note: Horizonから、SlackかSMS通知を送る設定を行う場合は、対応するドライバの動作要件についても、確認する必要があります。
https://readouble.com/laravel/5.8/ja/horizon.html#notifications

こちらの、「対応するドライバの動作要件」部分のリンク先が、

https://laravel.comnotifications.html/

というおかしなURLになってしまっているようです。

5.4以下はページ自体がなし、5.5, 5.6は公式サイトのドキュメントのリンクになっており、5.7, 5.8がリンク切れ、のようです。

**Comment by HiroKws** [comment]
原文に対して、リンクの修正をプルリクし、それを反映することで修正しました。該当部分だけ、絶対URLで記述されていました。ドキュメント間のリンクは相対URLで現在統一されています。

参考のために経緯を残しておくと、もともと原文のドキュメント内のリンクはバージョンを直接含む絶対URLで書かれていました。その後、バージョン部分は{{version}}に置き換わるようになり、その後に相対URLになりました。この時点で３通りの表記方法が存在しました。

readouble.comと原文とではURLの構造が違うために変換しています。３パターンを正規表現で変換するのは複雑でバギーでした。そして、全原文が{{version}}を使った相対URLへ統一されたため、それだけを変換する部分のみ残し、他のコードは削りました。

今回は、該当部分だけ絶対URLで書かれていたため、変換が対応できずに不正なURLとなっていました。5.8に関してはプルリクを送り原文を修正しました。５．７はメンテ期間切れですので、直接翻訳のMarkdownファイルを修正することで対応しました。
