### ISSUE TITLE
Eloquent：リレーションのページのサンプルコードに地の文が混じっている個所がある

### ISSUE THREAD

**Issue by magai** [laravel-ja/ja-docs-5.8#7]
https://readouble.com/laravel/5.8/ja/eloquent-relationships.html#defining-custom-intermediate-table-models

こちらの直下のサンプルコードに、以下のように地の文がサンプルコードに混じってしまっている個所があります。

```php
<?phpDefining Custom Intermediate Table Models
```

**Comment by HiroKws** [comment]
ありがとうございます。修正いたしました。

**Comment by magai** [comment]
こちらこそありがとうございました！
