### ISSUE TITLE
ライフサイクルでHTTPカーネルの記述について

### ISSUE THREAD

**Issue by TimLeaf** [laravel-ja/ja-docs-5.8#8]
https://readouble.com/laravel/5.8/ja/lifecycle.html

>HTTPカーネルはIlluminate\Foundation\Http\Kernelクラスを拡張しており、リクエストの実行前に処理されるbootstrappers（起動コード）の配列を定義しています。

上記の翻訳について、
bootstrappers（起動コード）の配列が定義されているところですが、原文からも、ソースで確認したら、Illuminate\Foundation\Http\Kernelクラスに定義されています。
下記のような翻訳は明確ではないと思っています。

HTTPカーネルはIlluminate\Foundation\Http\Kernelクラスを拡張しております。Illuminate\Foundation\Http\Kernelクラスでは、リクエストの実行前に処理されるbootstrappers（起動コード）の配列が定義されています。

日本語も、英語も、私の母国語ではないので、
認識の確認も含めて、issueを提出させていただきました。
よろしくお願いします。

英語の原文：

https://laravel.com/docs/5.8/lifecycle

> The HTTP kernel extends the Illuminate\Foundation\Http\Kernel class, which defines an array of bootstrappers that will be run before the request is executed.

**Comment by HiroKws** [comment]
ありがとうございました。

提案された翻訳を多少変更し、反映しました。

文章の後半がHTTPカーネルの説明なのか、Kernelクラスの説明なのか明確ではないのは日本語翻訳も、英語原文も同じだと思います。個人的見解ですが、原文の途中のカンマ(、)がなければwhichはKernelクラスを明確に修飾すると思いますが、存在している場合はHTTPカーネルとKernelクラス両方を修飾する可能性があります。

原文が不明瞭な場合でも、ソースコードを確認していません。翻訳にかかる手間がかかりすぎるからです。これが有料のサービスであれば私は確認しますが、無料のボランティアですので、そこまでの手間（コスト）は書けられません。

そのため文章の明確化は、今回のようなご指摘に頼っています。

**Comment by TimLeaf** [comment]
こちらこそ、ありがとうございました！

私にとしては、英語より日本語が慣れていますので、
感謝しております！
